# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hit < Formula
  desc "HTTP requests made sane again."
  homepage "https://github.com/hbagdi/hit"
  version "0.2.0"

  on_macos do
    url "https://github.com/hbagdi/hit/releases/download/v0.2.0/hit_0.2.0_darwin_all.tar.gz"
    sha256 "f1a00807dae186b71060aba88f69fbfcea2aa62654139d902a151e7c155e023d"

    def install
      bin.install "hit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hbagdi/hit/releases/download/v0.2.0/hit_0.2.0_linux_arm64.tar.gz"
      sha256 "de2ad54d637c89a7052775164cb4be9b2fc8f9b090f4d83841b057dd3390027a"

      def install
        bin.install "hit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hbagdi/hit/releases/download/v0.2.0/hit_0.2.0_linux_amd64.tar.gz"
      sha256 "fdf5ef6b9cbebddc94456f7ddd3ce75a47ac84ab5cc25aa720d388cb3bb099c4"

      def install
        bin.install "hit"
      end
    end
  end

  test do
    system "#{bin}/hit", "version"
  end
end
