# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hit < Formula
  desc "HTTP requests made sane again."
  homepage "https://github.com/hbagdi/hit"
  version "0.1.0"

  on_macos do
    url "https://github.com/hbagdi/hit/releases/download/v0.1.0/hit_0.1.0_darwin_all.tar.gz"
    sha256 "9cd292aafde68834b1670649ddcec50de77b8fb06fa64ea4024854ff0f5c1cb9"

    def install
      bin.install "hit"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hbagdi/hit/releases/download/v0.1.0/hit_0.1.0_linux_amd64.tar.gz"
      sha256 "393588093d883ddd659c1249c5ad9b1962b2951a6131cf0d3aba0af35831aac3"

      def install
        bin.install "hit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hbagdi/hit/releases/download/v0.1.0/hit_0.1.0_linux_arm64.tar.gz"
      sha256 "09fbfe07150d213cff3b748591cce0a9defbcd88e8c4c0f700c79f8833710619"

      def install
        bin.install "hit"
      end
    end
  end

  test do
    system "#{bin}/hit", "version"
  end
end
