# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Y2j < Formula
  desc "YAML to JSON converter"
  homepage "https://github.com/hbagdi/y2j"
  version "1.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hbagdi/y2j/releases/download/v1.0.0/y2j_1.0.0_darwin_amd64.tar.gz"
      sha256 "e19ce1b4e9c190287f826217dbc578ba57cff97aaa16888209ce9686ab3db6af"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hbagdi/y2j/releases/download/v1.0.0/y2j_1.0.0_linux_amd64.tar.gz"
      sha256 "a2ad4e7bc419e5f7966622d9cbdc8effb60735243dd58d4cb4ca93c04dc52583"
    end
  end

  def install
    bin.install "y2j"
  end

  test do
    system "#{bin}/y2j", "-help"
  end
end
